---
- hosts: deploy
  become: true
  vars:
    my_container: clinic
    my_image: ajitsingh25/spring-petclinic

  pre_tasks:
    - shell: echo "Ensure Docker Installed"

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: remove container
      docker_container:
        name: "{{ my_container }}"
        state: absent

    - name: Pull default Docker image
      docker_image:
        name: "{{ my_image }}"
        source: pull

    - name: Create Container
      docker_container:
        name: "{{ my_container }}"
        image: "{{ my_image }}"
        state: started
        ports:
         - "8080:8080"
  
  post_tasks:
    - shell: echo 'goodbye'
